config/routes.rb
Rails.application.routes.draw do
  
  resources :addemails
  resources :lists do  
  get "email","healthy", on: :collection
  post :sendma, on: :collection, as: :sendma   
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  get 'choices/choose'  
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/addemail.rb
class Addemail < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/addemails_controller.rb
class AddemailsController < ApplicationController
  before_action :set_addemail, only: [:show, :edit, :update, :destroy]

  # GET /addemails
  # GET /addemails.json
  def index
    @addemails = Addemail.all
  end

  # GET /addemails/1
  # GET /addemails/1.json
  def show
  end

  # GET /addemails/new
  def new
    @addemail = Addemail.new
  end

  # GET /addemails/1/edit
  def edit
  end

  # POST /addemails
  # POST /addemails.json
  def create
    @addemail = Addemail.new(addemail_params)

    respond_to do |format|
      if @addemail.save
        format.html { redirect_to email_lists_path, notice: 'Addemail was successfully created.' }
        format.json { render :show, status: :created, location: @addemail }
      else
        format.html { render :new }
        format.json { render json: @addemail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addemails/1
  # PATCH/PUT /addemails/1.json
  def update
    respond_to do |format|
      if @addemail.update(addemail_params)
        format.html { redirect_to @addemail, notice: 'Addemail was successfully updated.' }
        format.json { render :show, status: :ok, location: @addemail }
      else
        format.html { render :edit }
        format.json { render json: @addemail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addemails/1
  # DELETE /addemails/1.json
  def destroy
    @addemail.destroy
    respond_to do |format|
      format.html { redirect_to addemails_url, notice: 'Addemail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_addemail
      @addemail = Addemail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def addemail_params
      params.require(:addemail).permit(:extraemail, :currentemail)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  def choose
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
	@menu = @lists.sample(7)
	session[:pass_variable] = @menu
  end
  
  def sendma      
	@user = User.all
	@email = current_user.email
	
	@addemailsV = Addemail.all	
	@addemails = @addemailsV.where(currentemail: @email).pluck(:extraemail)
	
    @name = current_user.username	
	@menu = session[:pass_variable]
	ExampleMailer.sample_email(@email, @name, @menu, @addemails).deliver  	
	redirect_to (email_lists_path)
  end
  
  def healthy
  @lists = List.all
  @menu = @lists.where(healthy: 'True')
  end
  
  def email
  @lists = List.all
  @addemails = Addemail.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end
  
 
  


  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to choices_choose_path, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
	 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :ingredients, :healthy, :username, :email)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/addemails_helper.rb
module AddemailsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/addemails/_form.html.erb
<center>
<%= form_with(model: addemail, local: true) do |form| %>
  <% if addemail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(addemail.errors.count, "error") %> prohibited this addemail from being saved:</h2>

      <ul>
      <% addemail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"Who Else?" %>
    <%= form.text_field :extraemail, id: :addemail_extraemail, placeholder: "me@foodme.com"%>
  </div>

  
    
    
	<%= form.hidden_field :currentemail, id: :addemail_currentemail, value: current_user.email %>
  

  <div class="actions">
    
	<%= form.submit :class => "btn btn btn-primary", value: "Add This Person" %>
  </div>
<% end %>

app/views/addemails/edit.html.erb
<h1>Editing Addemail</h1>

<%= render 'form', addemail: @addemail %>

<%= link_to 'Show', @addemail %> |
<%= link_to 'Back', addemails_path %>

app/views/addemails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addemails</h1>

<table>
  <thead>
    <tr>
      <th>Extraemail</th>
      <th>Currentemail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addemails.each do |addemail| %>
      <tr>
        <td><%= addemail.extraemail %></td>
        <td><%= addemail.currentemail %></td>
        <td><%= link_to 'Show', addemail %></td>
        <td><%= link_to 'Edit', edit_addemail_path(addemail) %></td>
        <td><%= link_to 'Destroy', addemail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Addemail', new_addemail_path %>

app/views/addemails/new.html.erb
<h1>New Addemail</h1>
<br><br><br><br>
<%= render 'form', addemail: @addemail %>

<%= link_to 'Back', addemails_path %>

app/views/addemails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Extraemail:</strong>
  <%= @addemail.extraemail %>
</p>

<p>
  <strong>Currentemail:</strong>
  <%= @addemail.currentemail %>
</p>

<%= link_to 'Edit', edit_addemail_path(@addemail) %> |
<%= link_to 'Back', addemails_path %>

app/views/choices/choose.html.erb
<br><br><br><br><br><br><br><br><br><br><br><br><br><center>
<% if user_signed_in? %>
<%= link_to("Generate A Meal Prep", lists_path, :class => "btn btn-primary btn-xl") %>
<%= link_to("Add Item To Meal Prep", new_list_path, :class => "btn btn-primary btn-xl") %>
<%else%>
please sign in
<%end%>

<br><br><br><br><br><br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodme</title>
	<%= favicon_link_tag asset_path('Carrot.ico'), :rel => 'icon' %>
    <%= csrf_meta_tags %>
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
	  
        
		<%= link_to("foodme", root_path, :class => "navbar-brand js-scroll-trigger") %>
		
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
		  
            <li class="nav-item mx-0 mx-lg-1">
				<%= link_to "Get Started", choices_choose_path, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger'  %>
              
            </li>
			
			<% if user_signed_in? %>
			
            
			<li class="nav-item mx-0 mx-lg-1">
			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger'  %>
			</li>
			
			<% else %>
			
            <li class="nav-item mx-0 mx-lg-1">
			  <%= link_to "Sign In", new_user_session_path, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger'  %>              
            </li>
			<li class="nav-item mx-0 mx-lg-1">
			 <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger'  %>              
            </li>
			
			<% end %> 
          </ul>
        </div>
      </div>
    </nav>

    <!-- Header -->
	 
  

  
    <%= yield %>
	
    <!-- Footer -->
    <footer class="footer text-center">
      <div class="container">
        <div class="row">
          <div class="col-md-4 mb-5 mb-lg-0">
            <h4 class="text-uppercase mb-4">Location</h4>
            <p class="lead mb-0">Canada
              <br>Ontario</p>
          </div>
          <div class="col-md-4 mb-5 mb-lg-0">
            <h4 class="text-uppercase mb-4">Around the Web</h4>
            <ul class="list-inline mb-0">
              <li class="list-inline-item">
                <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                  <i class="fab fa-fw fa-facebook-f"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                  <i class="fab fa-fw fa-google-plus-g"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                  <i class="fab fa-fw fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                  <i class="fab fa-fw fa-linkedin-in"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                  <i class="fab fa-fw fa-dribbble"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <h4 class="text-uppercase mb-4">About Us</h4>
            <p class="lead mb-0">Foodme is free to use
              
          </div>
        </div>
      </div>
    </footer>

    <div class="copyright py-4 text-center text-white">
      <div class="container">
        <small>Copyright &copy; Your Website 2018</small>
      </div>
    </div>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
      <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
        <i class="fa fa-chevron-up"></i>
      </a>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container">

<h1>Hi
<%= current_user.username %></h1><br>


  
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="div_id_name" class="form-group">
  
    <%= form.label :name, :class => "control-label col-md-4  requiredField"%>
	 <div class="controls col-md-8 ">
    <%= form.text_field :name, :class => "input-md  textinput textInput form-control", id: :list_name, placeholder: "example: lasagna"%>
	</div>
  </div>
  
    <div id="div_id_name" class="form-group">
  
    <%= form.label :ingredients, :class => "control-label col-md-4  requiredField"%>
	 <div class="controls col-md-8 ">
    <%= form.text_field :ingredients, :class => "input-md  textinput textInput form-control", id: :list_ingredients, placeholder: "example: cheese noodles sauce"%>
	</div>
  </div>
  
      <div id="div_id_name" class="form-group">
  
    <%= form.label :healthy, :class => "control-label col-md-4  requiredField"%>
	 <div class="controls col-md-8 ">
    <%= form.check_box :healthy, :class => "input-md  textinput textInput form-control", id: :list_healthy %>
	</div>
  </div>
  
  
  <%= form.hidden_field :username, id: :liat_username, value: current_user.username %>
  <%= form.hidden_field :email, id: :liat_username, value: current_user.email %>



  <div class="btn btn-primar">
    <%= form.submit :class => "btn btn btn-primary", value: "Add Meal" %>
  </div>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/email.html.erb
<br><br><br><br><br><br><center>
<h3>Sending to: <%=current_user.email%><br> AND<br></h3>
<table>
  <thead>
    <tr>
      
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addemails.each do |addemail| %>
      <tr>
        <td><%= addemail.extraemail %></td>
        
        
        <td><%= link_to 'Edit', edit_addemail_path(addemail) %></td>
        <td><%= link_to 'Destroy', addemail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<center>
<%= link_to 'Add more people!', new_addemail_path, :class => 'btn btn-primary btn-m' %><br>
<%= button_to "Send This List", sendma_lists_path, :class => 'btn btn-primary btn-m'  %>

app/views/lists/healthy.html.erb
<p id="notice"><%= notice %></p>

<br><br><br><br><br><br>

<% @menu %>

<% day = ["Mon","Tues","Wed","Thurs","Fri","Sat","Sun"] %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Day</th>
      <th>Name</th>
	  <th>Ingredients</th>
      <th>Healthy</th>
      <th>Username</th>
	  <th>Email</th>
      <th colspan="4"></th>
    </tr>      
  </thead>

  <tbody>
  
  
     <% @menu.each.with_index do |list, index| %>

    <% i= index %>
    <tr>
        <td> <%=day[index]%></td>
		<td><%= list.name %></td>
        <td><%= list.ingredients %></td>
        <td><%= list.healthy %></td>
        <td><%= list.username %></td>
        <td><%= list.email %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Remove', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

	

		
    <% end %>
	
	

  </tbody>
</table>

<br>


<br><center>
<%= link_to("Re-Roll", lists_path, :class => "btn btn-primary btn-m") %>
<%= link_to("Add An Item", new_list_path, :class => "btn btn-primary btn-m") %>
<%= link_to("Regular", lists_path, :class => "btn btn-primary btn-m") %>
<%= link_to("Email Us This List", email_lists_path, :class => "btn btn-primary btn-m") %>

<br><br>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<br><br><br><br><br><br>

<% @menu %>

<% day = ["Mon","Tues","Wed","Thurs","Fri","Sat","Sun"] %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Day</th>
      <th>Name</th>
	  <th>Ingredients</th>
      <th>Healthy</th>
      <th>Username</th>
	  <th>Email</th>
      <th colspan="4"></th>
    </tr>      
  </thead>

  <tbody>
  
  
     <% @menu.each.with_index do |list, index| %>

    <% i= index %>
    <tr>
        <td> <%=day[index]%></td>
		<td><%= list.name %></td>
        <td><%= list.ingredients %></td>
        <td><%= list.healthy %></td>
        <td><%= list.username %></td>
        <td><%= list.email %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Remove', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

	

		
    <% end %>
	
	

  </tbody>
</table>

<br>


<br><center>
<%= link_to("Re-Roll", lists_path, :class => "btn btn-primary btn-m") %>
<%= link_to("Add An Item", new_list_path, :class => "btn btn-primary btn-m") %>
<%= link_to("Only Healthy", healthy_lists_path, :class => "btn btn-primary btn-m") %>
<%= link_to("Email Us This List", email_lists_path, :class => "btn btn-primary btn-m") %>

<br><br>

app/views/lists/new.html.erb
<h1>New List</h1>
<br><br><br><br><br>
<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @list.ingredients %>
</p>

<p>
  <strong>Healthy:</strong>
  <%= @list.healthy %>
</p>

<p>
  <strong>Username:</strong>
  <%= @list.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @list.email %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/welcome/index.html.erb
  <header class="masthead bg-primary text-white text-center">
      <div class="container">
	   <%= image_tag("profile.png", class: "img-fluid mb-5 d-block mx-auto") %>
        
        <h1 class="text-lowercase mb-0">foodme</h1>
        <hr class="star-light">
        <h2 class="font-weight-light mb-0">Get Preps - Make Preps - Share Preps</h2>
      </div>
    </header>

 

    <!-- Contact Section -->
    <section id="contact">
      <div class="container">
        <h2 class="text-center text-uppercase text-secondary mb-0">Contact Me</h2>
        <hr class="star-dark mb-5">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
            <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
            <form name="sentMessage" id="contactForm" novalidate="novalidate">
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>Name</label>
                  <input class="form-control" id="name" type="text" placeholder="Name" required="required" data-validation-required-message="Please enter your name.">
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>Email Address</label>
                  <input class="form-control" id="email" type="email" placeholder="Email Address" required="required" data-validation-required-message="Please enter your email address.">
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>Phone Number</label>
                  <input class="form-control" id="phone" type="tel" placeholder="Phone Number" required="required" data-validation-required-message="Please enter your phone number.">
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>Message</label>
                  <textarea class="form-control" id="message" rows="5" placeholder="Message" required="required" data-validation-required-message="Please enter a message."></textarea>
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <br>
              <div id="success"></div>
              <div class="form-group">
                <button type="submit" class="btn btn-primary btn-xl" id="sendMessageButton">Send</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>


   